### ISSUE TITLE
No response on terminal Mac

### ISSUE THREAD

**Issue by belsyuen** [ethcore/ethabi#15]
Hi, 
I am having trouble getting response from ethabi

I have tried 
1) cargo install (v1.0.0)
2) brew install (v0.2.0)
and
when I execute both bin files, the terminal recognise the command but nothing happens. Please could you let me know if this is a known issue?

Thanks!

**Comment by debris** [comment]
hey @belsyuen 

There was indeed an issue with missing cli features flag in [README.md](https://github.com/ethcore/ethabi/pull/16) and in [brew formula](https://github.com/ethcore/homebrew-ethcore/pull/38)

Please try again using either

- cargo
    ```
    cargo install ethabi --features='cli'
    ```

- brew
    ```
    brew install ethabi
    ```

**Comment by belsyuen** [comment]
hey! it worked! thanks!
