### ISSUE TITLE
Contract types as parameters give InvalidType

### ISSUE THREAD

**Issue by mbrock** [ethcore/ethabi#7]
Solidity contracts can of course use contracts as parameters.

```
igloo:~*$ ethabi encode params -v address 4444444444444444444444444444444444444444
0000000000000000000000004444444444444444444444444444444444444444
igloo:~*$ ethabi encode params -v MyContract 4444444444444444444444444444444444444444
error: Param(InvalidType)
```

Would it be reasonable to just interpret any type starting with a capital letter as being synonymous with `address`? Otherwise I'll have to mogrify my `abi` JSON and do that substitution myself.

**Comment by debris** [comment]
Hey!

How did you create `abi` JSON with contract names as params? I've never seen such abi. Just tried the following contract

contract:

```solidity
contract Foo {}

contract Bar {
    function bar(Foo foo) {}
}
```

generated abi:
```json
[
  {
    "constant": false,
    "inputs": [
      {
        "name": "foo",
        "type": "address"
      }
    ],
    "name": "bar",
    "outputs": [
      
    ],
    "type": "function"
  }
]
```

I used solidity version `0.3.6-3fc68da5/Release-Emscripten/clang` from [here](https://ethereum.github.io/browser-solidity/#version=0.3.6).

**Comment by mbrock** [comment]
Ah, I see, it seems to only happen with events.

```
contract Foo {
}

contract Bar {
  event E(Foo x);
  function f(Foo x);
}
```

gives

```
[
  {
    "constant": false,
    "inputs": [
      {
        "name": "x",
        "type": "address"
      }
    ],
    "name": "f",
    "outputs": [],
    "type": "function"
  },
  {
    "anonymous": false,
    "inputs": [
      {
        "indexed": false,
        "name": "x",
        "type": "Foo"
      }
    ],
    "name": "E",
    "type": "event"
  }
```

**Comment by debris** [comment]
Interesting... I've opened an issue upstream in solidity repo. Let's wait for the answer

**Comment by mbrock** [comment]
Cool, thanks. For now I'm doing the transform to `address` myself.

**Comment by dbrock** [comment]
Looks like this was fixed in Solidity right after you guys reported it!

**Comment by debris** [comment]
Great! I'm closing it :)
